tasks:
  - init: |
      echo "myapp" | npx @backstage/create-app
      cd myapp && yarn dev
      docker run --name your-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres

  - name: Initialize 
    command: |
       echo "Almost ready - Running the PostgreSQL container (note: when the workspace is first started up, these commands both fail - please ignore) "
       docker start your-postgres


ports:
  # Backstage Web Application
  - port: 3000
    onOpen: open-preview
    visibility: public

  # Backstage Backend API
  - port: 3000
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - ms-azuretools.vscode-docker    