tasks:
  - init: |
      gp open README.md
      docker run --name backstage-postgres -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres
      echo "myapp" | npx @backstage/create-app
      # runnnig Backstage with local PostgreSQL database is not yet successful 
      # cp app-config.local.yaml myapp
      cd myapp
      # yarn add --cwd packages/backend pg
      yarn dev

  - name: Initialize 
    command: |
       echo "Almost ready - Running the PostgreSQL container (note: when the workspace is first started up, these commands both fail - please ignore) "
       docker start backstage-postgres


ports:
  # Backstage Web Application
  - port: 3000
    onOpen: open-preview
    visibility: public

  # Backstage Backend API
  - port: 7007
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - ms-azuretools.vscode-docker    