# Backstage override configuration for your local development environment
backend:
  database:
    client: pg
    connection:
      host: 127.0.0.1
      port: 5432
      user: postgres
      password: mysecretpassword